export interface WordPuzzle {
  hint: string;       // English sentence (the puzzle prompt)
  hindi: string;      // Hindi translation
  hintWord: string;   // Multi-word helpful hint (NEVER the answer itself)
  answer: string;     // one-word answer
  difficulty?: 1 | 2 | 3;
}

export const wordCategories: Record<string, { label: string; emoji: string; puzzles: WordPuzzle[] }> = {
  general: {
    label: "General Knowledge",
    emoji: "🌍",
    puzzles: [
      { hint: "The capital of the country famous for the Eiffel Tower and croissants.", hindi: "एफिल टावर और क्रोसां के लिए मशहूर देश की राजधानी।", hintWord: "city of love, lights, and Seine river", answer: "paris", difficulty: 1 },
      { hint: "The largest ocean on Earth, lying between Asia and the Americas.", hindi: "एशिया और अमेरिका के बीच फैला पृथ्वी का सबसे बड़ा महासागर।", hintWord: "starts with P, covers nearly a third of the planet", answer: "pacific", difficulty: 1 },
      { hint: "The longest river in the world, flowing north through Egypt.", hindi: "मिस्र से होकर उत्तर की ओर बहने वाली दुनिया की सबसे लंबी नदी।", hintWord: "ancient pharaohs built pyramids on its banks", answer: "nile", difficulty: 2 },
      { hint: "The highest mountain on Earth, on the Nepal–Tibet border.", hindi: "नेपाल और तिब्बत की सीमा पर पृथ्वी की सबसे ऊँची चोटी।", hintWord: "named after a British surveyor general", answer: "everest", difficulty: 2 },
      { hint: "The currency used across most countries in the European Union.", hindi: "अधिकांश यूरोपीय संघ देशों में इस्तेमाल होने वाली मुद्रा।", hintWord: "introduced in 1999, symbol looks like a curvy E", answer: "euro", difficulty: 2 },
      { hint: "The smallest planet in our solar system, closest to the Sun.", hindi: "सूर्य के सबसे करीब, हमारे सौरमंडल का सबसे छोटा ग्रह।", hintWord: "also the name of a Roman messenger god", answer: "mercury", difficulty: 2 },
      { hint: "The country with the largest population, home to the Great Wall.", hindi: "दुनिया की सबसे बड़ी आबादी वाला देश, जहाँ ग्रेट वॉल है।", hintWord: "Asian giant whose flag has five yellow stars", answer: "china", difficulty: 2 },
      { hint: "The science of living things, taught in school with cells and DNA.", hindi: "जीवित प्राणियों का विज्ञान, स्कूल में कोशिका और DNA पढ़ाते हैं।", hintWord: "bio means life in Greek", answer: "biology", difficulty: 2 },
      { hint: "The element with chemical symbol 'Au', valued in jewellery.", hindi: "रासायनिक चिन्ह 'Au' वाला तत्व, गहनों में बहुत कीमती।", hintWord: "shiny yellow precious metal", answer: "gold", difficulty: 1 },
      { hint: "The desert that covers most of northern Africa.", hindi: "उत्तरी अफ्रीका के अधिकांश हिस्से में फैला रेगिस्तान।", hintWord: "world's largest hot desert, name means 'desert' in Arabic", answer: "sahara", difficulty: 3 },
      { hint: "The number that, multiplied by itself, gives one hundred.", hindi: "वो संख्या जिसे खुद से गुणा करने पर सौ मिलता है।", hintWord: "square root of 100", answer: "ten", difficulty: 1 },
      { hint: "The continent that is also a single country, famous for kangaroos.", hindi: "वो महाद्वीप जो एक ही देश है, कंगारुओं के लिए मशहूर।", hintWord: "Sydney Opera House and the Outback are here", answer: "australia", difficulty: 2 },
      { hint: "The brightest star we see — actually our nearest one.", hindi: "हमें दिखने वाला सबसे चमकीला तारा — असल में हमारे सबसे करीब का।", hintWord: "gives us daylight and warmth", answer: "sun", difficulty: 1 },
      { hint: "The country shaped like a boot, famous for pizza and pasta.", hindi: "बूट जैसा आकार, पिज़्ज़ा और पास्ता के लिए मशहूर देश।", hintWord: "Rome is its capital", answer: "italy", difficulty: 2 },
      { hint: "The currency used in Japan.", hindi: "जापान में उपयोग होने वाली मुद्रा।", hintWord: "symbol is ¥, three letters", answer: "yen", difficulty: 3 },
    ],
  },
  cars: {
    label: "Cars",
    emoji: "🚗",
    puzzles: [
      { hint: "A German luxury brand whose logo has four interlocked rings.", hindi: "जर्मन लग्ज़री ब्रांड जिसके लोगो में चार जुड़े छल्ले हैं।", hintWord: "starts with A, owned by Volkswagen group", answer: "audi", difficulty: 1 },
      { hint: "An Italian sports car brand with a black prancing horse on yellow.", hindi: "पीले बैकग्राउंड पर काले घोड़े वाले लोगो की इतालवी स्पोर्ट्स कार कंपनी।", hintWord: "founded by Enzo, races in Formula 1 in red", answer: "ferrari", difficulty: 1 },
      { hint: "An American electric car company led by Elon Musk.", hindi: "एलोन मस्क के नेतृत्व वाली अमेरिकी इलेक्ट्रिक कार कंपनी।", hintWord: "named after a Serbian-American inventor", answer: "tesla", difficulty: 1 },
      { hint: "India's largest car maker, makers of Swift, Alto and Brezza.", hindi: "भारत की सबसे बड़ी कार कंपनी — स्विफ्ट, ऑल्टो, ब्रेज़ा बनाती है।", hintWord: "joint venture with Suzuki", answer: "maruti", difficulty: 2 },
      { hint: "A bull-logo Italian supercar brand from Sant'Agata.", hindi: "बैल के लोगो वाली एक इतालवी सुपरकार कंपनी।", hintWord: "started by a tractor maker who fought with Ferrari", answer: "lamborghini", difficulty: 3 },
      { hint: "Japanese brand famous for the GT-R and the 350Z.", hindi: "GT-R और 350Z के लिए मशहूर जापानी कार ब्रांड।", hintWord: "owns Datsun and partners with Renault", answer: "nissan", difficulty: 3 },
      { hint: "The British luxury sedan with the Spirit of Ecstasy mascot.", hindi: "स्पिरिट ऑफ़ एक्स्टसी हुड ऑर्नामेंट वाली ब्रिटिश लग्ज़री सेडान।", hintWord: "double-R logo, ultra-premium", answer: "rollsroyce", difficulty: 3 },
      { hint: "South Korean maker of the Creta and the Verna.", hindi: "क्रेटा और वेर्ना बनाने वाली दक्षिण कोरियाई कंपनी।", hintWord: "slanted H logo, sister brand of Kia", answer: "hyundai", difficulty: 2 },
      { hint: "The German brand whose three-pointed star sits on every model.", hindi: "तीन कोनों वाला सितारा जिसके हर मॉडल पर होता है — जर्मन ब्रांड।", hintWord: "S-Class is its flagship sedan", answer: "mercedes", difficulty: 2 },
      { hint: "The American muscle car maker, home of the Mustang.", hindi: "मस्टैंग बनाने वाली अमेरिकी मसल कार कंपनी।", hintWord: "blue oval logo, started by Henry", answer: "ford", difficulty: 2 },
      { hint: "Bavarian brand known by 'The Ultimate Driving Machine'.", hindi: "'The Ultimate Driving Machine' स्लोगन वाला बवारियन ब्रांड।", hintWord: "blue and white roundel logo, M Sport division", answer: "bmw", difficulty: 2 },
      { hint: "Japanese brand famous for the Civic, City and the NSX supercar.", hindi: "सिविक, सिटी और NSX सुपरकार के लिए मशहूर जापानी ब्रांड।", hintWord: "also the world's largest motorcycle maker", answer: "honda", difficulty: 2 },
      { hint: "Indian brand that makes the Nexon EV and the Harrier SUV.", hindi: "नेक्सॉन EV और हैरियर SUV बनाने वाला भारतीय ब्रांड।", hintWord: "salt-to-software conglomerate, owns Jaguar Land Rover", answer: "tata", difficulty: 2 },
      { hint: "Swedish carmaker now famous for safety and pure-electric SUVs.", hindi: "सुरक्षा और पूरी तरह इलेक्ट्रिक SUV के लिए मशहूर स्वीडिश कार कंपनी।", hintWord: "name is Latin for 'I roll', owned by Geely", answer: "volvo", difficulty: 3 },
      { hint: "British SUV brand famous for the Defender and the Range Rover.", hindi: "डिफेंडर और रेंज रोवर के लिए मशहूर ब्रिटिश SUV ब्रांड।", hintWord: "two words combined: terrain + explorer (single word)", answer: "landrover", difficulty: 3 },
    ],
  },
  cartoons: {
    label: "Cartoons",
    emoji: "🧸",
    puzzles: [
      { hint: "A Japanese boy with a butt-shaking dance, lives with Misae and Hiroshi.", hindi: "एक जापानी लड़का जो डांस करता है, मिसाए और हिरोशी का बेटा।", hintWord: "5-year-old menace, his action song is famous in India", answer: "shinchan", difficulty: 1 },
      { hint: "A yellow square fellow who lives in a pineapple under the sea.", hindi: "समुद्र के नीचे अनानास में रहने वाला एक पीला चौकोर किरदार।", hintWord: "fry-cook at the Krusty Krab with Patrick", answer: "spongebob", difficulty: 1 },
      { hint: "A blue robotic cat from the 22nd century who helps a lazy boy.", hindi: "22वीं सदी से आया नीला रोबोट बिल्ला जो आलसी लड़के की मदद करता है।", hintWord: "pulls gadgets out of a four-dimensional pocket", answer: "doraemon", difficulty: 1 },
      { hint: "A boy trainer travelling Kanto trying to catch them all.", hindi: "कांटो में घूमने वाला एक लड़का ट्रेनर जो सबको पकड़ना चाहता है।", hintWord: "best friend is an electric yellow mouse", answer: "ash", difficulty: 2 },
      { hint: "An eternal cat-and-mouse chase animated since 1940.", hindi: "1940 से चलने वाली एक बिल्ली और चूहे की कभी न खत्म होने वाली दौड़।", hintWord: "the cat is grey, the mouse is brown — names rhyme", answer: "tomandjerry", difficulty: 2 },
      { hint: "An orange ninja from the Hidden Leaf, dreams of becoming Hokage.", hindi: "हिडन लीफ का एक नारंगी निंजा जो होकेज बनना चाहता है।", hintWord: "loves ramen, has a nine-tailed fox sealed inside him", answer: "naruto", difficulty: 3 },
      { hint: "A small explorer girl with her monkey friend Boots.", hindi: "अपने बंदर दोस्त बूट्स के साथ छोटी एक्सप्लोरर लड़की।", hintWord: "carries a talking purple backpack and map", answer: "dora", difficulty: 1 },
      { hint: "A pink panther in a slim suit who rarely speaks.", hindi: "सूट पहने एक गुलाबी पैंथर जो बहुत कम बोलता है।", hintWord: "comedy cartoon with a famous Henry Mancini saxophone tune", answer: "pinkpanther", difficulty: 2 },
      { hint: "A clueless cat owned by Garfield's owner, eats lasagna all day.", hindi: "लसानिया खाने वाला आलसी और मोटा नारंगी कार्टून बिल्ला।", hintWord: "hates Mondays, loves Jon and Odie", answer: "garfield", difficulty: 2 },
      { hint: "A sponge-haired boy from Springfield with a baby sister Maggie.", hindi: "स्प्रिंगफील्ड का एक पीला लड़का जिसकी छोटी बहन मैगी है।", hintWord: "skateboards a lot, son of Homer", answer: "bart", difficulty: 2 },
      { hint: "A cartoon mouse who started Disney, wears red shorts.", hindi: "डिज़्नी की शुरुआत करने वाला कार्टून चूहा जो लाल पैंट पहनता है।", hintWord: "Minnie's boyfriend, has Pluto as a pet", answer: "mickey", difficulty: 1 },
      { hint: "A bald cartoon boy whose grandpa lived in a small Indian village.", hindi: "एक गंजा कार्टून लड़का जिसके दादा भारतीय गाँव में रहते थे।", hintWord: "Indian boy genius, name rhymes with 'know'", answer: "chhota", difficulty: 2 },
      { hint: "A Japanese boy detective shrunk into a child by a poison.", hindi: "एक ज़हर से बच्चा बना जापानी लड़का जासूस।", hintWord: "wears glasses, real name is Shinichi Kudo", answer: "conan", difficulty: 3 },
      { hint: "A magical girl group fighting evil — leader's name is Usagi.", hindi: "बुराई से लड़ने वाली एक जादुई लड़कियों की टोली, लीडर का नाम उसागी है।", hintWord: "moon-themed sailor warriors, 1990s anime", answer: "sailormoon", difficulty: 3 },
    ],
  },
  movies: {
    label: "Movies",
    emoji: "🎬",
    puzzles: [
      { hint: "A wizard boy with a lightning scar who studies at Hogwarts.", hindi: "बिजली के निशान वाला जादूगर लड़का जो हॉगवर्ट्स में पढ़ता है।", hintWord: "has a phoenix wand and a snowy owl named Hedwig", answer: "harry", difficulty: 1 },
      { hint: "An animated kingdom of ice ruled by a queen with magical powers.", hindi: "जादुई शक्तियों वाली रानी द्वारा शासित बर्फ का एक एनिमेटेड साम्राज्य।", hintWord: "Anna and Olaf the snowman are also in it", answer: "frozen", difficulty: 1 },
      { hint: "A masked vigilante who protects Gotham City at night.", hindi: "रात में गॉथम शहर की रक्षा करने वाला नकाबपोश हीरो।", hintWord: "his butler is Alfred, his enemy is the Joker", answer: "batman", difficulty: 1 },
      { hint: "A Bollywood film about three engineering friends — 'All is well'.", hindi: "तीन इंजीनियरिंग दोस्तों पर बनी बॉलीवुड फिल्म — 'All is well'।", hintWord: "Aamir Khan plays Rancho", answer: "3idiots", difficulty: 2 },
      { hint: "A green ogre who lives in a swamp with a talking donkey.", hindi: "एक हरा राक्षस जो बात करते गधे के साथ दलदल में रहता है।", hintWord: "marries Princess Fiona, voiced by Mike Myers", answer: "shrek", difficulty: 2 },
      { hint: "A sci-fi epic about a galaxy far, far away with lightsabers.", hindi: "बहुत दूर की एक आकाशगंगा की लाइटसेबर वाली विज्ञान-कथा महाकाव्य।", hintWord: "Yoda, Luke, Vader and the Force", answer: "starwars", difficulty: 3 },
      { hint: "Bollywood film about an autistic man searching across India for God.", hindi: "भगवान की तलाश में भारत भर में घूमने वाले ऑटिस्टिक आदमी की फ़िल्म।", hintWord: "Salman Khan calls a girl 'Munni'", answer: "bajrangi", difficulty: 3 },
      { hint: "A Disney princess who loses a glass slipper at midnight.", hindi: "आधी रात में काँच की चप्पल खोने वाली डिज़्नी राजकुमारी।", hintWord: "fairy godmother, pumpkin carriage, mean stepsisters", answer: "cinderella", difficulty: 1 },
      { hint: "An action film franchise about a fast and furious street-racing crew.", hindi: "तेज़ रफ़्तार स्ट्रीट रेसिंग गैंग की एक एक्शन फ़िल्म सीरीज़।", hintWord: "Vin Diesel plays Dom Toretto, family is everything", answer: "fastandfurious", difficulty: 2 },
      { hint: "A movie about dinosaurs cloned and brought back to a theme park.", hindi: "थीम पार्क में क्लोन करके वापस लाए गए डायनासोरों की फ़िल्म।", hintWord: "T-Rex chase, by Steven Spielberg, set on a tropical island", answer: "jurassicpark", difficulty: 3 },
      { hint: "Animated Pixar film about a rat who dreams of being a chef in Paris.", hindi: "पेरिस में शेफ बनने के सपने देखने वाले चूहे की पिक्सर फ़िल्म।", hintWord: "Remy controls Linguini by pulling his hair", answer: "ratatouille", difficulty: 3 },
      { hint: "Bollywood film of two lovers, one Indian one Pakistani — Bajirao's director.", hindi: "एक भारतीय और एक पाकिस्तानी प्रेमियों की बॉलीवुड फिल्म, बाजीराव डायरेक्टर की।", hintWord: "Salman & Aishwarya, song 'Tadap Tadap'", answer: "hum", difficulty: 3 },
      { hint: "A Disney lion cub who must reclaim his throne after his father's death.", hindi: "अपने पिता की मौत के बाद राज्य वापस लेने वाला एक डिज़्नी शेर का बच्चा।", hintWord: "Hakuna Matata, Mufasa, Scar, Pumbaa", answer: "lionking", difficulty: 2 },
      { hint: "Sci-fi where humans plug into a virtual world; red pill or blue pill.", hindi: "विज्ञान-कथा जहाँ इंसान वर्चुअल दुनिया से जुड़ते हैं — लाल या नीली गोली।", hintWord: "Neo, Morpheus, Trinity, agent Smith", answer: "matrix", difficulty: 3 },
      { hint: "Indian Telugu epic about a warrior asking 'why did Kattappa kill Baahubali?'.", hindi: "तेलुगु महाकाव्य जिसमें पूछा गया 'कट्टप्पा ने बाहुबली को क्यों मारा?'।", hintWord: "Prabhas in the lead, directed by Rajamouli", answer: "baahubali", difficulty: 2 },
    ],
  },
  marvel: {
    label: "Marvel",
    emoji: "🦸",
    puzzles: [
      { hint: "Billionaire genius who builds a red-and-gold suit of armour.", hindi: "लाल-सुनहरा कवच बनाने वाला अरबपति जीनियस।", hintWord: "Tony Stark, snaps his fingers in Endgame", answer: "ironman", difficulty: 1 },
      { hint: "A patriotic super-soldier who carries a vibranium shield.", hindi: "वाइब्रेनियम ढाल लिए एक देशभक्त सुपर-सिपाही।", hintWord: "Steve Rogers, frozen in ice for decades", answer: "captainamerica", difficulty: 1 },
      { hint: "Asgardian god of thunder who wields the hammer Mjolnir.", hindi: "मजोलनिर हथौड़ा उठाने वाला आसगार्ड का बिजली का देवता।", hintWord: "long blonde hair, brother of Loki", answer: "thor", difficulty: 1 },
      { hint: "A scientist whose anger turns him into a green giant.", hindi: "एक वैज्ञानिक जिसका गुस्सा उसे हरा दैत्य बना देता है।", hintWord: "Bruce Banner, smash!", answer: "hulk", difficulty: 1 },
      { hint: "A teenage hero from Queens who shoots webs and climbs walls.", hindi: "क्वींस का किशोर हीरो जो जाला फेंकता है और दीवारों पर चढ़ता है।", hintWord: "bitten by a radioactive arachnid, Peter Parker", answer: "spiderman", difficulty: 1 },
      { hint: "A purple titan who collects six powerful stones.", hindi: "छह ताकतवर पत्थर इकट्ठा करने वाला बैंगनी टाइटन।", hintWord: "wields the Infinity Gauntlet, born on Titan", answer: "thanos", difficulty: 2 },
      { hint: "Wakanda's king with a vibranium suit of his namesake animal.", hindi: "वकांडा का राजा जिसका सूट उसी जानवर के नाम का है।", hintWord: "T'Challa, the animal is also a leopard species", answer: "blackpanther", difficulty: 2 },
      { hint: "A mutant with claws of adamantium and a fast healing power.", hindi: "अडामेंटियम पंजों और तेज़ हीलिंग ताकत वाला म्यूटेंट।", hintWord: "Hugh Jackman's iconic role, X-Men member, named after an animal", answer: "wolverine", difficulty: 2 },
      { hint: "The mischievous Asgardian god, Thor's adopted brother.", hindi: "थॉर का गोद लिया हुआ शरारती आसगार्डियन भाई।", hintWord: "horned green helmet, god of mischief", answer: "loki", difficulty: 2 },
      { hint: "A red-haired master spy on the Avengers.", hindi: "एवेंजर्स की एक लाल बालों वाली मास्टर जासूस।", hintWord: "Natasha Romanoff, ex-KGB, sacrificed on Vormir", answer: "blackwidow", difficulty: 2 },
      { hint: "A wizard who became Sorcerer Supreme after a car accident.", hindi: "कार दुर्घटना के बाद सॉर्सरर सुप्रीम बना एक जादूगर।", hintWord: "Stephen, Cloak of Levitation, Eye of Agamotto", answer: "doctorstrange", difficulty: 3 },
      { hint: "A foul-mouthed talking raccoon from a guardian team.", hindi: "गार्डियंस टीम का बदतमीज़ बोलने वाला रैकून।", hintWord: "best friend is a tree named Groot", answer: "rocket", difficulty: 3 },
      { hint: "An air-force pilot turned cosmic hero — Higher, Further, Faster.", hindi: "एयर-फ़ोर्स पायलट से बनी एक कॉस्मिक हीरो।", hintWord: "Carol Danvers, glowing yellow energy blasts", answer: "captainmarvel", difficulty: 3 },
      { hint: "A fast-healing assassin who breaks the fourth wall in red suit.", hindi: "लाल सूट में चौथी दीवार तोड़ने वाला तेज़ हीलिंग वाला हत्यारा।", hintWord: "Ryan Reynolds, very rude, mouthy mercenary", answer: "deadpool", difficulty: 2 },
      { hint: "Tiny hero who can shrink and ride atomic insects.", hindi: "छोटा हीरो जो सिकुड़कर परमाणु कीड़ों पर सवारी कर सकता है।", hintWord: "Scott Lang, the insect is a six-legged worker", answer: "antman", difficulty: 2 },
    ],
  },
  dragonball: {
    label: "Dragon Ball",
    emoji: "🐉",
    puzzles: [
      { hint: "The Saiyan main hero raised on Earth, loves food and fighting.", hindi: "धरती पर पला हुआ सायन मुख्य हीरो, खाने और लड़ने का शौकीन।", hintWord: "trained by Master Roshi, signature move 'Kamehameha'", answer: "goku", difficulty: 1 },
      { hint: "The proud Saiyan prince, Goku's eternal rival.", hindi: "गर्वीला सायन राजकुमार, गोकू का हमेशा का प्रतिद्वंद्वी।", hintWord: "wears blue-and-white armour, married to Bulma", answer: "vegeta", difficulty: 1 },
      { hint: "Goku's first son who fought Cell as a Super Saiyan 2.", hindi: "गोकू का पहला बेटा जिसने सुपर सायन 2 बनकर सेल से लड़ाई की।", hintWord: "wears glasses as an adult, scholar fighter", answer: "gohan", difficulty: 2 },
      { hint: "A bald, three-eyed monk and Goku's best friend.", hindi: "एक गंजा त्रिनेत्री भिक्षु, गोकू का सबसे अच्छा दोस्त।", hintWord: "married to Android 18, signature Destructo Disc", answer: "krillin", difficulty: 2 },
      { hint: "A pink frosty alien tyrant who destroyed Planet Vegeta.", hindi: "गुलाबी ठंडा एलियन तानाशाह जिसने वेगेटा ग्रह को नष्ट किया।", hintWord: "transforms multiple times, name sounds like cold storage", answer: "frieza", difficulty: 2 },
      { hint: "The bio-android made of cells from the strongest fighters.", hindi: "सबसे ताकतवर लड़ाकों की कोशिकाओं से बना बायो-एंड्रॉइड।", hintWord: "perfect form has green skin and a tail, Saga named after him", answer: "cell", difficulty: 3 },
      { hint: "The pink chubby villain that absorbs people, made of clay magic.", hindi: "लोगों को सोखने वाला गुलाबी मोटा खलनायक, मिट्टी के जादू से बना।", hintWord: "child form is good, 'Buu' is in the name", answer: "majinbuu", difficulty: 3 },
      { hint: "A short blue-haired genius who loves Vegeta and runs Capsule Corp.", hindi: "नीले बालों वाली एक जीनियस जो वेगेटा से प्यार करती है, कैप्सूल कॉर्प चलाती है।", hintWord: "Trunks's mother, lifelong Goku friend", answer: "bulma", difficulty: 2 },
      { hint: "Vegeta's purple-haired son from the future who carries a sword.", hindi: "भविष्य से आया वेगेटा का बैंगनी बालों वाला तलवारबाज बेटा।", hintWord: "warned the Z fighters about the androids", answer: "trunks", difficulty: 2 },
      { hint: "Old turtle hermit who taught Goku the Kamehameha.", hindi: "बूढ़ा कछुआ साधु जिसने गोकू को कामेहामेहा सिखाया।", hintWord: "wears sunglasses and a Hawaiian shirt, perverted", answer: "roshi", difficulty: 2 },
      { hint: "The grey shape-shifting cat who is Goku's childhood friend.", hindi: "रूप बदलने वाली ग्रे बिल्ली, गोकू की बचपन की दोस्त।", hintWord: "always with Yamcha, name rhymes with 'duar'", answer: "puar", difficulty: 3 },
      { hint: "Goku's youngest son with a wild personality.", hindi: "गोकू का सबसे छोटा बेटा, बहुत शरारती स्वभाव का।", hintWord: "fuses with Trunks to make Gotenks", answer: "goten", difficulty: 2 },
      { hint: "Antagonist god in DBS who destroys universes, blue and feline.", hindi: "DBS का खलनायक देव जो ब्रह्मांडों को मिटाता है, नीला बिल्ली जैसा।", hintWord: "Universe 7's God of Destruction, eats with Whis", answer: "beerus", difficulty: 3 },
      { hint: "The mystical orange spheres that grant any one wish.", hindi: "नारंगी रहस्यमयी गेंदें जो कोई भी एक इच्छा पूरी करती हैं।", hintWord: "seven of them summon Shenron the dragon", answer: "dragonballs", difficulty: 1 },
      { hint: "Goku's wife and Gohan's mother, very strict.", hindi: "गोकू की पत्नी और गोहान की माँ, बहुत सख्त।", hintWord: "daughter of the Ox-King, name means 'milk' in Chinese", answer: "chichi", difficulty: 3 },
    ],
  },
  anime: {
    label: "Anime",
    emoji: "🍥",
    puzzles: [
      { hint: "A boy who eats a Devil Fruit and becomes a stretchy pirate king hopeful.", hindi: "डेविल फ्रूट खाकर रबर बना एक लड़का जो पाइरेट किंग बनना चाहता है।", hintWord: "wears a straw hat, captain of the Going Merry", answer: "luffy", difficulty: 1 },
      { hint: "Twin-blade swordsman in black who fights titans.", hindi: "काले कपड़ों में दो तलवारों वाला योद्धा जो टाइटन्स से लड़ता है।", hintWord: "main hero of Attack on Titan, can become a Titan himself", answer: "eren", difficulty: 2 },
      { hint: "A boy whose family is killed and sister is turned into a demon.", hindi: "जिसके परिवार को मार दिया गया और बहन राक्षस बन गई — एक लड़का।", hintWord: "Demon Slayer protagonist, water-breathing then sun-breathing", answer: "tanjiro", difficulty: 2 },
      { hint: "Boy ninja exiled from Hidden Leaf, has Sharingan eyes.", hindi: "हिडन लीफ से निकाला गया एक लड़का निंजा, जिसकी आँखें शारिंगन वाली हैं।", hintWord: "Naruto's rival and friend, Uchiha clan", answer: "sasuke", difficulty: 2 },
      { hint: "A shy boy whose body is full of cursed energy after eating a finger.", hindi: "एक उँगली खाने के बाद जिसके शरीर में शापित ऊर्जा भर गई — एक शर्मीला लड़का।", hintWord: "Jujutsu Kaisen protagonist, Sukuna's vessel", answer: "yuji", difficulty: 3 },
      { hint: "A genius detective who challenges a god-like killer using a notebook.", hindi: "नोटबुक से मारने वाले देव-जैसे हत्यारे को चुनौती देता एक जीनियस जासूस।", hintWord: "from Death Note, sits crouched, eats sweets", answer: "l", difficulty: 3 },
      { hint: "A pilot of a giant robot called Eva-01 with a violet colour scheme.", hindi: "EVA-01 नाम के बैंगनी विशाल रोबोट का पायलट।", hintWord: "Evangelion lead, son of Gendo", answer: "shinji", difficulty: 3 },
      { hint: "A blonde alchemist with a metal arm seeking the Philosopher's Stone.", hindi: "धातु की बांह वाला सुनहरे बालों का अल्केमिस्ट जो पारस पत्थर ढूँढ रहा है।", hintWord: "Fullmetal Alchemist, brother is a soul in armour", answer: "edward", difficulty: 3 },
      { hint: "A boy with green hair born without a quirk in a hero school.", hindi: "हीरो स्कूल में बिना क्वर्क के पैदा हुआ हरे बालों वाला लड़का।", hintWord: "My Hero Academia, idolises All Might, named Deku", answer: "izuku", difficulty: 3 },
      { hint: "The most powerful sorcerer with white hair and blindfold.", hindi: "सफेद बालों और आंखों पर पट्टी वाला सबसे शक्तिशाली जादूगर।", hintWord: "Jujutsu Kaisen teacher, has the Six Eyes and Limitless", answer: "gojo", difficulty: 3 },
      { hint: "Cute pink-cheeked electric mouse Pokémon and Ash's partner.", hindi: "गुलाबी गालों वाला बिजली का प्यारा पोकेमॉन, ऐश का साथी।", hintWord: "yellow rodent, says its own name", answer: "pikachu", difficulty: 1 },
      { hint: "A short orange-haired volleyball boy who loves to spike.", hindi: "वॉलीबॉल खेलने वाला छोटे कद, नारंगी बालों वाला लड़का।", hintWord: "Haikyuu protagonist, jumps like a crow", answer: "hinata", difficulty: 2 },
      { hint: "A boy with a robotic right arm who hunts demons in 1900s Japan.", hindi: "1900 के जापान में राक्षसों का शिकार करने वाला रोबोटिक दाहिने हाथ का लड़का।", hintWord: "Chainsaw Man's Denji's friend? No — Demon Slayer's Inosuke? No — Hint: anime is 'Dororo'", answer: "hyakkimaru", difficulty: 3 },
      { hint: "A devil-hearted boy who turns his head into a chainsaw.", hindi: "जिसका सिर चेनसॉ में बदल जाता है — एक राक्षस-दिल वाला लड़का।", hintWord: "Pochita is his pet devil dog", answer: "denji", difficulty: 3 },
      { hint: "A spirit detective who comes back from death to fight demons.", hindi: "मरने के बाद वापस लौटकर राक्षसों से लड़ने वाला एक स्पिरिट डिटेक्टिव।", hintWord: "Yu Yu Hakusho protagonist, Spirit Gun is his move", answer: "yusuke", difficulty: 3 },
    ],
  },
  food: {
    label: "Food",
    emoji: "🍕",
    puzzles: [
      { hint: "A round Italian flatbread with cheese, sauce and toppings.", hindi: "गोल इतालवी रोटी जिस पर पनीर, सॉस और टॉपिंग होती है।", hintWord: "Margherita and Pepperoni are popular kinds", answer: "pizza", difficulty: 1 },
      { hint: "A spicy yellow Indian rice dish from Hyderabad with meat or veg.", hindi: "हैदराबाद की मसालेदार पीली चावल वाली डिश, मीट या सब्ज़ी के साथ।", hintWord: "layered with saffron and fried onions, dum-cooked", answer: "biryani", difficulty: 1 },
      { hint: "A small fried Indian street snack — hollow puris with spicy water.", hindi: "मसालेदार पानी से भरी छोटी फूली पूरी — भारतीय स्ट्रीट स्नैक।", hintWord: "called pani-puri or gol-gappa elsewhere", answer: "panipuri", difficulty: 2 },
      { hint: "A Japanese dish of vinegared rice with raw fish or vegetables.", hindi: "सिरके के चावल पर कच्ची मछली या सब्ज़ी वाला जापानी व्यंजन।", hintWord: "rolled with seaweed nori, eaten with wasabi", answer: "sushi", difficulty: 1 },
      { hint: "A South Indian crispy fermented crepe usually served with chutney.", hindi: "दक्षिण भारतीय कुरकुरा फेंटा हुआ क्रेप, चटनी के साथ।", hintWord: "made from rice and urad dal batter", answer: "dosa", difficulty: 1 },
      { hint: "A Mexican folded corn or wheat shell filled with meat and salsa.", hindi: "मांस और साल्सा से भरा मैक्सिकन मक्के या गेहूँ का मुड़ा हुआ शेल।", hintWord: "famously served on Tuesdays", answer: "taco", difficulty: 2 },
      { hint: "A frozen sweet dairy dessert often eaten in a cone.", hindi: "कोन में खाया जाने वाला जमा हुआ मीठा दूध डेसर्ट।", hintWord: "vanilla, chocolate, strawberry — ice ___", answer: "icecream", difficulty: 1 },
      { hint: "A North Indian dish of chicken cooked in a creamy spiced tomato sauce.", hindi: "क्रीमी मसालेदार टमाटर ग्रेवी में बना उत्तर भारतीय चिकन।", hintWord: "named after a small dairy fat used in cooking", answer: "butterchicken", difficulty: 2 },
      { hint: "Italian tube-shaped or twisted wheat dish, often with red sauce.", hindi: "अक्सर लाल सॉस के साथ खाया जाने वाला इतालवी ट्यूब/मरोड़ा गेहूँ का व्यंजन।", hintWord: "spaghetti, penne, fusilli are types of it", answer: "pasta", difficulty: 1 },
      { hint: "A sweet baked food with layers and frosting, eaten on birthdays.", hindi: "जन्मदिन पर खाई जाने वाली परतों और क्रीम वाली मीठी पकी हुई चीज़।", hintWord: "you blow candles on top of it", answer: "cake", difficulty: 1 },
      { hint: "A Japanese noodle soup popularised in instant packs.", hindi: "जापानी नूडल सूप जो इंस्टैंट पैकेट से दुनिया भर में फैला।", hintWord: "topped with egg, pork, nori — Naruto loves it", answer: "ramen", difficulty: 2 },
      { hint: "A Punjabi flatbread stuffed with potato or paneer, served with butter.", hindi: "आलू या पनीर की पंजाबी भरी रोटी, मक्खन के साथ खाई जाती है।", hintWord: "stuffed paratha with two-letter starter prefix", answer: "paratha", difficulty: 2 },
      { hint: "A creamy Italian rice dish slow-cooked with stock, often with mushrooms.", hindi: "स्टॉक में धीरे पकाया गया क्रीमी इतालवी चावल, अक्सर मशरूम के साथ।", hintWord: "uses arborio rice, finished with parmesan", answer: "risotto", difficulty: 3 },
      { hint: "A Korean fermented spicy cabbage side dish.", hindi: "कोरियाई किण्वित मसालेदार बंद गोभी का साइड डिश।", hintWord: "served with almost every Korean meal, red chili", answer: "kimchi", difficulty: 3 },
      { hint: "A Middle Eastern dip of mashed chickpeas, tahini and lemon.", hindi: "चने, ताहिनी और नींबू का मध्य-पूर्वी डिप।", hintWord: "served with pita bread and olive oil", answer: "hummus", difficulty: 3 },
    ],
  },
  sports: {
    label: "Sports",
    emoji: "⚽",
    puzzles: [
      { hint: "Argentine football GOAT who lifted the World Cup in 2022.", hindi: "अर्जेंटीना का फुटबॉल GOAT जिसने 2022 का विश्व कप उठाया।", hintWord: "left foot magician, plays for Inter Miami, ten letters in last name? No — first name short", answer: "messi", difficulty: 1 },
      { hint: "Indian cricket batter known as 'Captain Cool', World Cup 2011.", hindi: "'कैप्टन कूल' के नाम से मशहूर भारतीय बल्लेबाज, 2011 विश्व कप जीता।", hintWord: "wicketkeeper from Ranchi, helicopter shot", answer: "dhoni", difficulty: 1 },
      { hint: "Portuguese striker famous for the 'siu' celebration.", hindi: "'सिउ' सेलिब्रेशन के लिए मशहूर पुर्तगाली स्ट्राइकर।", hintWord: "wears jersey number 7, played for Real Madrid", answer: "ronaldo", difficulty: 1 },
      { hint: "American basketball legend with six NBA titles for the Bulls.", hindi: "बुल्स के साथ छह NBA खिताब जीतने वाली अमेरिकी बास्केटबॉल लीजेंड।", hintWord: "Air ___, jersey number 23, has a sneaker brand", answer: "jordan", difficulty: 2 },
      { hint: "Indian cricket batter known as 'God of Cricket', has 100 international centuries.", hindi: "'क्रिकेट का भगवान' कहलाने वाले भारतीय बल्लेबाज, 100 अंतरराष्ट्रीय शतक।", hintWord: "Mumbai Indian, hometown of his name initials SRT", answer: "sachin", difficulty: 1 },
      { hint: "Swiss tennis legend with elegant single-handed backhand, 20 grand slams.", hindi: "एक हाथ के बैकहैंड और 20 ग्रैंड स्लैम वाले सुंदर खेल वाले स्विस टेनिस लेजेंड।", hintWord: "rivalry with Nadal and Djokovic, Wimbledon king", answer: "federer", difficulty: 2 },
      { hint: "Football tournament held every four years for national teams.", hindi: "हर चार साल में राष्ट्रीय टीमों के बीच होने वाला फुटबॉल टूर्नामेंट।", hintWord: "FIFA's biggest event, Argentina won the latest", answer: "worldcup", difficulty: 1 },
      { hint: "Olympic event of running 42.195 km in one go.", hindi: "एक बार में 42.195 किलोमीटर दौड़ने का ओलंपिक आयोजन।", hintWord: "named after a Greek city and a battle", answer: "marathon", difficulty: 2 },
      { hint: "Indian cricket fast bowler called the 'Yorker King', wears 93.", hindi: "'यॉर्कर किंग' कहलाने वाले 93 नंबर के भारतीय तेज़ गेंदबाज़।", hintWord: "from Ahmedabad, married to a film actress", answer: "bumrah", difficulty: 3 },
      { hint: "Sport with a yellow ball, racquets and grass courts at Wimbledon.", hindi: "विंबलडन की घास की कोर्ट पर पीले बॉल और रैकेट का खेल।", hintWord: "you serve, volley and smash; love means zero", answer: "tennis", difficulty: 1 },
      { hint: "Sport played on ice with a stick and a rubber puck.", hindi: "बर्फ पर स्टिक और रबर पक से खेला जाने वाला खेल।", hintWord: "Canada's national winter sport", answer: "hockey", difficulty: 2 },
      { hint: "Indian women's wrestler who won Commonwealth gold, biopic 'Dangal'.", hindi: "कॉमनवेल्थ गोल्ड जीतने वाली भारतीय महिला पहलवान, 'दंगल' फिल्म।", hintWord: "two sisters, surname rhymes with 'patil'", answer: "phogat", difficulty: 3 },
      { hint: "Sport that uses 18 holes, clubs and a small white ball.", hindi: "18 गड्ढे, क्लब और एक छोटी सफेद गेंद वाला खेल।", hintWord: "Tiger Woods is the most famous player", answer: "golf", difficulty: 1 },
      { hint: "World's most-watched cricket league, 10 Indian city teams.", hindi: "दुनिया की सबसे ज़्यादा देखी जाने वाली क्रिकेट लीग, 10 भारतीय शहरों की टीमें।", hintWord: "abbreviated I.P.L., starts every March", answer: "ipl", difficulty: 1 },
      { hint: "Spanish football club known as Los Blancos with 14 UCL titles.", hindi: "14 UCL ट्रॉफी जीतने वाला स्पेनिश फुटबॉल क्लब, 'लॉस ब्लांकोस'।", hintWord: "city's name + 'royal' in Spanish", answer: "realmadrid", difficulty: 2 },
    ],
  },
};

export const categoryKeys = Object.keys(wordCategories);

// Flatten for daily challenge selection
export const allPuzzles: WordPuzzle[] = Object.values(wordCategories).flatMap((c) => c.puzzles);
